# Generated by Django 5.0.3 on 2024-03-23 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capital", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("Africa", "Africa"),
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("North America", "North America"),
                            ("South America", "South America"),
                            ("Oceania", "Oceania"),
                        ],
                        max_length=100,
                    ),
                ),
                ("climate_zone", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("flag_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "safety_index",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("safety_and_security", models.TextField(blank=True, null=True)),
                ("broadband_speed", models.IntegerField(blank=True, null=True)),
                ("mobile_speed", models.IntegerField(blank=True, null=True)),
                ("internet_accessibility", models.TextField(blank=True, null=True)),
                ("cost_of_living", models.IntegerField(blank=True, null=True)),
                ("avg_rent_cost", models.IntegerField(blank=True, null=True)),
                (
                    "healthcare_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "cultural_and_recreational_opportunities",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CountryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="countries/")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("cover_photo", models.ImageField(upload_to="profile_photo/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("★☆☆☆☆", "One Star"),
                            ("★★☆☆☆", "Two Stars"),
                            ("★★★☆☆", "Three Stars"),
                            ("★★★★☆", "Four Stars"),
                            ("★★★★★", "Five Stars"),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        related_query_name="review",
                        to="api.country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Digital Nomad Visa", max_length=255),
                ),
                ("visa_cost", models.CharField(blank=True, max_length=255, null=True)),
                ("income_requirements", models.TextField(blank=True, null=True)),
                ("visa_length", models.TextField(blank=True, null=True)),
                (
                    "citizens_that_qualify",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "apply_remotely",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bonus", models.TextField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visas",
                        to="api.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visas",
                "ordering": ["country"],
            },
        ),
    ]
