# Generated by Django 5.0.3 on 2024-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_country_humidity_country_temperature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="humidity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="temperature",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="uv_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
